import { WechatyBuilder } from 'wechaty'

const bot = WechatyBuilder.build({
  name: 'ding-dong-bot',
  puppet: 'wechaty-puppet-service',
})

bot
  .on('scan', (qrcode, status) =>
    console.log(`Scan QR Code to login: ${status}\nhttps://wechaty.js.org/qrcode/${encodeURIComponent(qrcode)}`),
  )
  .on('login', user => console.log(`User ${user} logged in`))
  .on('message', async message => {
    console.log(`Message: ${message}`)

    if (message.text() === 'ding') {
      await message.say('dong')
    }
  })

bot.start()
