name: Run WeChaty Bot

on:
  push:
    branches:
      - main

jobs:
  bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 添加这一段：设置环境变量
      - name: Set up PadLocal token
        run: echo "Token set"
        env:
          WECHATY_PUPPET_PADLOCAL_TOKEN: ${{ secrets.WECHATY_PUPPET_PADLOCAL_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Run the bot
        run: node index.js
